### ISSUE TITLE
Hi, dear bgottschall 

### ISSUE THREAD

**Issue by shylockyuan** [bgottschall/reloc#1]

**Comment by shylockyuan** [comment]
Hi, dear bgottschall
       I feel greatful to your contribution of your FPGA relocation sources！
	   I have some questions about the relocation design:
	   
	   Q1: Take the "zedboard_example" as an example, when I transfer the logic circuits form prc_0 partition to prc_1 partition, then the logic circuits in prc_0 before 
	   will be in prc_1 partition, thus whether the prc_0 partition will be a black box(blanking function)?
	   
	   Q2: If I want to design a project which has 1 static modoule, 4PRRs and 3 partial reconfigurable moudles (PRM)which both can be put in each of the 4 PRRs. 
	       Especally, 3PRMs are in cooperative work ,for example 3bits full_adder are divided into three 1bits full_adder, each of them serve as a PRM.
		   
	       At the same time, there  will be one PRM in one PRR and the rest PRR should be filled with a blanking moudule, for example, 
		   at first, I put PRM0 in the PRR0,PRM1 in the PRR1,PRM2 in the PRR2,a blanking moudule in the PRR3,then  all the PRMs shift together(or one by one),
		   so now PRM0 in the PRR1,PRM1 in the PRR2,PRM2 in the PRR3,at the same time a blanking moudule in the PRR0.
		   
		   I don't know whether I can make use of your source to make my design?  Would you give me some suggestions about my thoughts?
		
		thank u very much!

**Comment by bgottschall** [comment]
Sorry for the late reply,

Q1: when you have logic in prc_0 then you can create bitstreams that fit all other prc. The content of prc_0 is still the same until you have reconfigured it. You are not relocating at runtime, you are relocating bitstreams which you can then freely configure into the relocatable regions.

Q2: This is currently not supported by this work. every design is isolated and can only communicated with the static region. If you want to connect multiple PR regions you have to do this through a communication channel of the static design.
