### ISSUE TITLE
relocater.c:(.text+0x497): undefined reference to 'be32toh' and 'strdup'

### ISSUE THREAD

**Issue by iDoka** [bgottschall/reloc#2]
I cant to build `relocater` because code base have undefined reference to these functions: `be32toh` and `strdup`

Related code string:
- https://github.com/bgottschall/reloc/blob/master/relocater/bitstreams.h#L80
- https://github.com/bgottschall/reloc/blob/fb0ce8b7910c6dc509739bd39e7e1236aa153fd0/relocater/relocater.c#L299

Could you fix broken dependency of func?

**Comment by bgottschall** [comment]
https://man7.org/linux/man-pages/man3/strdup.3.html
https://linux.die.net/man/3/be32toh

Compiles fine on x86. aarch64
